import type { Metadata } from "next";
import "@/app/utilities/style/globals.css";
import {ReactNode} from "react";
import {ThemeProvider} from "./utilities/providers";
import {AppFooter, AppHeader} from "@/widgets/general";
import {MainGutter} from "@/shared/utils/main-gutter";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`antialiased`}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
            <AppHeader />
            <MainGutter className='min-h-screen'>
                {children}
            </MainGutter>
            <AppFooter />
        </ThemeProvider>
      </body>
    </html>
  );
}
